name: Build and Deploy Code

on: ["push", "pull_request"]

jobs:
  job1:
    environment:
      name: testing
    env:
      DATABASE_TYPE: ${{secrets.DATABASE_TYPE}} 
      DATABASE_HOST: ${{secrets.DATABASE_HOST}} 
      DATABASE_PORT:  ${{secrets.DATABASE_PORT}} 
      DATABASE_NAME: ${{secrets.DATABASE_NAME}} 
      DATABASE_USER: ${{secrets.DATABASE_USER}} 
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}} 
      SECURITY_KEY: ${{secrets.SECURITY_KEY}} 
      ALGORITHM: ${{secrets.ALGORITHM}} 
      EXPIRE_IN: ${{secrets.EXPIRE_IN}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest
        run: |
          PYTHONPATH=. pytest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
        



